[package]
name = "rougeciv"
version = "0.1.0"
authors = ["James Daly <james@codenomads.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcod = "0.15"
noise = "0.6.0"